const CONFIG = window.AP_RETAIL_CONFIG;
const page = document.body.dataset.page;
const currency = new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB' });
const state = { client: null, user: null, store: null, products: [], cart: new Map(), selectedCategory: 'all' };
function message(id, text = '') { const node = document.getElementById(id); if (node) node.textContent = text; }
function empty(text) { return `<div class="empty-state">${text}</div>`; }
function formatMoney(amount) { return currency.format(Number(amount || 0)); }
function setLoading(loading) { const shell = document.getElementById('app-shell'); if (shell) { shell.classList.toggle('is-loading', loading); shell.setAttribute('aria-busy', String(loading)); } }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function assertConfig() { if (!CONFIG?.supabaseUrl || !CONFIG?.supabasePublishableKey || !window.supabase) throw new Error('ไม่พบการตั้งค่าการเชื่อมต่อระบบ กรุณาติดต่อผู้ดูแลระบบ'); state.client = window.supabase.createClient(CONFIG.supabaseUrl, CONFIG.supabasePublishableKey, { auth: { persistSession: true, autoRefreshToken: true } }); }
async function requireSession() { const { data, error } = await state.client.auth.getUser(); if (error || !data.user) { window.location.replace('index.html'); return false; } state.user = data.user; return true; }
async function loadContext() { const { data, error } = await state.client.rpc('retail_get_my_context'); if (error) throw new Error('ยังไม่สามารถเปิดสาขาได้: ' + error.message); if (!data?.store_id) throw new Error('บัญชีนี้ยังไม่มีสิทธิ์เข้าถึงสาขา Retail POS'); state.store = data; const context = document.getElementById('store-context'); if (context) context.textContent = data.store_name || 'สาขาที่ได้รับสิทธิ์'; const storeName = document.getElementById('settings-store'); if (storeName) storeName.textContent = data.store_name || '—'; const userName = document.getElementById('settings-user'); if (userName) userName.textContent = state.user.email || '—'; }
async function loadProducts() { const { data, error } = await state.client.rpc('retail_list_store_products', { p_search: '', p_category: null }); if (error) throw error; state.products = data || []; renderProducts(); renderCatalog(); renderInventory(); renderMovementProducts(); }
function renderProducts() { const grid = document.getElementById('product-grid'); const chips = document.getElementById('category-chips'); if (!grid) return; const term = (document.getElementById('product-search')?.value || '').trim().toLowerCase(); const visible = state.products.filter((item) => (state.selectedCategory === 'all' || item.category_name === state.selectedCategory) && (!term || `${item.name} ${item.sku || ''}`.toLowerCase().includes(term))); const categories = [...new Set(state.products.map((item) => item.category_name).filter(Boolean))]; if (chips) chips.innerHTML = [`<button class="chip ${state.selectedCategory === 'all' ? 'active' : ''}" data-category="all">ทั้งหมด</button>`, ...categories.map((name) => `<button class="chip ${state.selectedCategory === name ? 'active' : ''}" data-category="${escapeHtml(name)}">${escapeHtml(name)}</button>`)].join(''); grid.innerHTML = visible.length ? visible.map((item) => `<button class="product-card" data-add-product="${item.id}" type="button"><p>${escapeHtml(item.sku || 'ไม่มี SKU')}</p><h3>${escapeHtml(item.name)}</h3><p>${item.available_quantity ?? '—'} ${escapeHtml(item.unit_name || '')}</p><strong>${formatMoney(item.price)}</strong></button>`).join('') : empty('ยังไม่มีสินค้าที่พร้อมขายในสาขานี้'); }
function renderCatalog() { const list = document.getElementById('catalog-list'); if (!list) return; const term = (document.getElementById('catalog-search')?.value || '').trim().toLowerCase(); const rows = state.products.filter((item) => !term || `${item.name} ${item.sku || ''}`.toLowerCase().includes(term)); list.innerHTML = rows.length ? rows.map((item) => `<article class="catalog-row"><div><strong class="line-title">${escapeHtml(item.name)}</strong><span class="line-meta">${escapeHtml(item.sku || 'ไม่มี SKU')} · คงเหลือ ${item.available_quantity ?? '—'} ${escapeHtml(item.unit_name || '')}</span></div><div><strong>${formatMoney(item.price)}</strong><button data-edit-product="${item.id}" type="button">แก้ไข</button></div></article>`).join('') : empty('ยังไม่มีสินค้าในสาขานี้'); }
function renderInventory() { const list = document.getElementById('inventory-list'); if (!list) return; list.innerHTML = state.products.length ? state.products.map((item) => `<article class="catalog-row"><div><strong class="line-title">${escapeHtml(item.name)}</strong><span class="line-meta">${escapeHtml(item.sku || 'ไม่มี SKU')} · ${escapeHtml(item.unit_name || 'หน่วย')}</span></div><strong>${item.available_quantity ?? '—'}</strong></article>`).join('') : empty('ยังไม่มีรายการสต๊อกในสาขานี้'); }
function renderMovementProducts() { const selector = document.getElementById('movement-product'); if (selector) selector.innerHTML = `<option value="">เลือกสินค้า</option>${state.products.map((item) => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join(''); }
function renderCart() { const lines = document.getElementById('cart-lines'); const total = document.getElementById('cart-total'); const submit = document.getElementById('submit-sale'); if (!lines) return; const values = [...state.cart.values()]; const sum = values.reduce((value, line) => value + Number(line.price) * line.quantity, 0); lines.innerHTML = values.length ? values.map((line) => `<article class="cart-line"><div><strong class="line-title">${escapeHtml(line.name)}</strong><span class="line-meta">${formatMoney(line.price)} / ${escapeHtml(line.unit_name || 'หน่วย')}</span></div><div class="quantity-controls"><button data-cart-change="${line.id}" data-delta="-1" type="button">−</button><strong>${line.quantity}</strong><button data-cart-change="${line.id}" data-delta="1" type="button">+</button></div></article>`).join('') : empty('เลือกสินค้าสำหรับเริ่มรายการขาย'); if (total) total.textContent = values.length ? formatMoney(sum) : '—'; if (submit) submit.disabled = !values.length; }
function addToCart(id) { const item = state.products.find((product) => product.id === id); if (!item) return; const line = state.cart.get(id) || { ...item, quantity: 0 }; const available = Number(item.available_quantity); if (Number.isFinite(available) && line.quantity + 1 > available) { message('pos-message', 'จำนวนสินค้าในตะกร้าเกินสต๊อกที่ระบบยืนยัน'); return; } line.quantity += 1; state.cart.set(id, line); message('pos-message'); renderCart(); }
function changeCart(id, delta) { const line = state.cart.get(id); if (!line) return; const next = line.quantity + Number(delta); if (next <= 0) state.cart.delete(id); else { const available = Number(line.available_quantity); if (delta > 0 && Number.isFinite(available) && next > available) { message('pos-message', 'จำนวนสินค้าในตะกร้าเกินสต๊อกที่ระบบยืนยัน'); return; } line.quantity = next; state.cart.set(id, line); } renderCart(); }
async function submitSale() { const lines = [...state.cart.values()].map((line) => ({ store_product_id: line.id, quantity: line.quantity })); if (!lines.length) return; const button = document.getElementById('submit-sale'); button.disabled = true; message('pos-message', 'กำลังบันทึกรายการขาย…'); const { data, error } = await state.client.rpc('retail_create_pos_sale', { p_payment_method: document.getElementById('payment-method').value, p_lines: lines }); if (error) { button.disabled = false; message('pos-message', error.message); return; } state.cart.clear(); renderCart(); await loadProducts(); message('pos-message', `บันทึกรายการขายสำเร็จ เลขอ้างอิง ${data?.sale_number || 'ที่ระบบออกให้'}`); }
async function loadSales() { const list = document.getElementById('sales-list'); if (!list) return; const { data, error } = await state.client.rpc('retail_list_sales', { p_limit: 50 }); if (error) throw error; list.innerHTML = data?.length ? data.map((sale) => `<article class="sale-row"><div><strong class="line-title">${escapeHtml(sale.sale_number)}</strong><span class="line-meta">${new Date(sale.created_at).toLocaleString('th-TH')} · ${escapeHtml(sale.payment_method || '—')}</span></div><strong>${formatMoney(sale.grand_total)}</strong></article>`).join('') : empty('ยังไม่มีประวัติการขายในสาขานี้'); }
async function saveProduct(form) { const imageInput = document.getElementById('product-image'); const submit = form.querySelector('[type="submit"]'); submit.disabled = true; message('product-message', 'กำลังบันทึกสินค้า…'); try { const image = imageInput.files?.[0] ? await compressImage(imageInput.files[0]) : null; const payload = { id: document.getElementById('product-id').value || null, name: document.getElementById('product-name').value.trim(), sku: document.getElementById('product-sku').value.trim() || null, price: Number(document.getElementById('product-price').value), unit_name: document.getElementById('product-unit').value.trim(), image }; const { error } = await state.client.rpc('retail_upsert_store_product', { p_product: payload }); if (error) throw error; document.getElementById('product-dialog').close(); await loadProducts(); } catch (error) { message('product-message', error.message || 'ไม่สามารถบันทึกสินค้าได้'); } finally { submit.disabled = false; } }
async function saveMovement(form) { const submit = form.querySelector('[type="submit"]'); submit.disabled = true; message('movement-message', 'กำลังบันทึกรายการ…'); const { error } = await state.client.rpc('retail_record_inventory_movement', { p_store_product_id: document.getElementById('movement-product').value, p_movement_type: document.getElementById('movement-type').value, p_quantity: Number(document.getElementById('movement-quantity').value), p_reason: document.getElementById('movement-reason').value.trim() }); if (error) { message('movement-message', error.message); submit.disabled = false; return; } document.getElementById('movement-dialog').close(); await loadProducts(); submit.disabled = false; }
async function compressImage(file) { if (!file.type.startsWith('image/')) throw new Error('กรุณาเลือกไฟล์รูปภาพ'); const bitmap = await createImageBitmap(file); const scale = Math.min(1, 1200 / Math.max(bitmap.width, bitmap.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale); canvas.getContext('2d').drawImage(bitmap, 0, 0, canvas.width, canvas.height); return await new Promise((resolve, reject) => canvas.toBlob((blob) => { if (!blob) { reject(new Error('ไม่สามารถบีบอัดรูปภาพได้')); return; } const reader = new FileReader(); reader.onload = () => resolve({ name: `${crypto.randomUUID()}.jpg`, mime_type: 'image/jpeg', base64: String(reader.result).split(',')[1] }); reader.readAsDataURL(blob); }, 'image/jpeg', .82)); }
function bindHandlers() { document.addEventListener('click', async (event) => { const target = event.target.closest('[data-action],[data-add-product],[data-cart-change],[data-category],[data-edit-product]'); if (!target) return; if (target.dataset.action === 'signout') { await state.client.auth.signOut(); window.location.replace('index.html'); } if (target.dataset.addProduct) addToCart(target.dataset.addProduct); if (target.dataset.cartChange) changeCart(target.dataset.cartChange, target.dataset.delta); if (target.dataset.category) { state.selectedCategory = target.dataset.category; renderProducts(); } if (target.dataset.action === 'open-product-editor') { document.getElementById('product-form').reset(); document.getElementById('product-id').value = ''; document.getElementById('product-dialog-title').textContent = 'เพิ่มสินค้า'; document.getElementById('product-dialog').showModal(); } if (target.dataset.editProduct) { const product = state.products.find((item) => item.id === target.dataset.editProduct); if (!product) return; document.getElementById('product-id').value = product.id; document.getElementById('product-name').value = product.name || ''; document.getElementById('product-sku').value = product.sku || ''; document.getElementById('product-price').value = product.price || ''; document.getElementById('product-unit').value = product.unit_name || 'ชิ้น'; document.getElementById('product-dialog-title').textContent = 'แก้ไขสินค้า'; document.getElementById('product-dialog').showModal(); } if (target.dataset.action === 'open-movement') document.getElementById('movement-dialog').showModal(); }); document.getElementById('product-search')?.addEventListener('input', renderProducts); document.getElementById('catalog-search')?.addEventListener('input', renderCatalog); document.getElementById('clear-cart')?.addEventListener('click', () => { state.cart.clear(); renderCart(); }); document.getElementById('submit-sale')?.addEventListener('click', submitSale); document.getElementById('product-form')?.addEventListener('submit', (event) => { event.preventDefault(); saveProduct(event.currentTarget); }); document.getElementById('movement-form')?.addEventListener('submit', (event) => { event.preventDefault(); saveMovement(event.currentTarget); }); }
async function initSignin() { assertConfig(); document.getElementById('signin-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = event.currentTarget.querySelector('button'); button.disabled = true; message('signin-message', 'กำลังเข้าสู่ระบบ…'); const { error } = await state.client.auth.signInWithPassword({ email: document.getElementById('email').value.trim(), password: document.getElementById('password').value }); if (error) { button.disabled = false; message('signin-message', error.message); return; } window.location.replace('pos.html'); }); const { data } = await state.client.auth.getUser(); if (data.user) window.location.replace('pos.html'); }
async function initApp() { try { assertConfig(); if (!await requireSession()) return; bindHandlers(); await loadContext(); if (['pos', 'catalog', 'inventory'].includes(page)) await loadProducts(); if (page === 'sales') await loadSales(); if (page === 'pos') renderCart(); } catch (error) { const container = document.querySelector('.page-content'); if (container) container.innerHTML = `<section class="card"><div class="empty-state">${escapeHtml(error.message || 'ไม่สามารถเปิดข้อมูลได้')}</div></section>`; } finally { setLoading(false); } }
if (page === 'signin') initSignin().catch((error) => message('signin-message', error.message)); else initApp();
